# Generated by Django 3.0.9 on 2021-01-06 07:58

import account.models.account
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210106_0651'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.account',),
            managers=[
                ('objects', account.models.account.AccountManager()),
            ],
        ),
    ]
